//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hemrika.SharePresence.WebSite.ControlTemplates {
    
    
    public partial class GoogleTracking {
        
        /// <summary>
        /// tbl_Tracking control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hemrika.SharePresence.Google.Visualization.GVTable tbl_Tracking;
        
        /// <summary>
        /// org_tracking_prev control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hemrika.SharePresence.Google.Visualization.GVOrgChart org_tracking_prev;
        
        /// <summary>
        /// org_tracking_next control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Hemrika.SharePresence.Google.Visualization.GVOrgChart org_tracking_next;
    }
}
