//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hemrika.SharePresence.WebSite.Modules.GateKeeper {
	using System;
	
	
	public partial class SPGateKeeperContext : Microsoft.SharePoint.Linq.DataContext {
		
		#region Extensibility Method Definitions
		partial void OnCreated();
		#endregion
		
		public SPGateKeeperContext(string requestUrl) : 
				base(requestUrl) {
			this.OnCreated();
		}
		
		/// <summary>
		/// GateKeeper Description
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="GateKeeper")]
		public Microsoft.SharePoint.Linq.EntityList<Item> GateKeeper {
			get {
				return this.GetList<Item>("GateKeeper");
			}
		}
	}
	
	/// <summary>
	/// Create a new list item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(DroneEntry))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(GateKeeperEntry))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(HoneyPotEntry))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(HTTPEntry))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ProxyEntry))]
	public partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
		
		private System.Nullable<int> _id;
		
		private System.Nullable<int> _version;
		
		private string _path;
		
		private Microsoft.SharePoint.Linq.EntityState _entityState;
		
		private System.Collections.Generic.IDictionary<string, object> _originalValues;
		
		private string _title;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
			get {
				return this._entityState;
			}
			set {
				if ((value != this._entityState)) {
					this._entityState = value;
				}
			}
		}

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
			get {
				if ((null == this._originalValues)) {
					this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
				}
				return this._originalValues;
			}
		}
		
		public Item() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_id", ReadOnly=true, FieldType="Counter")]
		public System.Nullable<int> Id {
			get {
				return this._id;
			}
			set {
				if ((value != this._id)) {
					this.OnPropertyChanging("Id", this._id);
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_version", ReadOnly=true, FieldType="Integer")]
		public System.Nullable<int> Version {
			get {
				return this._version;
			}
			set {
				if ((value != this._version)) {
					this.OnPropertyChanging("Version", this._version);
					this._version = value;
					this.OnPropertyChanged("Version");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_path", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
		public string Path {
			get {
				return this._path;
			}
			set {
				if ((value != this._path)) {
					this.OnPropertyChanging("Path", this._path);
					this._path = value;
					this.OnPropertyChanged("Path");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_title", Required=true, FieldType="Text")]
		public virtual string Title {
			get {
				return this._title;
			}
			set {
				if ((value != this._title)) {
					this.OnPropertyChanging("Title", this._title);
					this._title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanged(string propertyName) {
			if ((null != this.PropertyChanged)) {
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		protected virtual void OnPropertyChanging(string propertyName, object value) {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			if ((false == this._originalValues.ContainsKey(propertyName))) {
				this._originalValues.Add(propertyName, value);
			}
			if ((null != this.PropertyChanging)) {
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
	}
	
	/// <summary>
	/// Create a new list item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Drone Entry", Id="0x010046EA71B010823F4193BDCAC6F54AC4B3")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(GateKeeperDroneEntry))]
	public partial class DroneEntry : Item {
		
		private System.Nullable<System.DateTime> _gateKeeperDate;
		
		private string _gateKeeperIPAddress;
		
		private string _gateKeeperUseragent;
		
		private string _gateKeeperReferrer;
		
		private System.Nullable<GateKeeper_Type> _gateKeeper_Type;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public DroneEntry() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Date", Storage="_gateKeeperDate", FieldType="DateTime")]
		public System.Nullable<System.DateTime> GateKeeperDate {
			get {
				return this._gateKeeperDate;
			}
			set {
				if ((value != this._gateKeeperDate)) {
					this.OnPropertyChanging("GateKeeperDate", this._gateKeeperDate);
					this._gateKeeperDate = value;
					this.OnPropertyChanged("GateKeeperDate");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_IPAddress", Storage="_gateKeeperIPAddress", FieldType="Text")]
		public string GateKeeperIPAddress {
			get {
				return this._gateKeeperIPAddress;
			}
			set {
				if ((value != this._gateKeeperIPAddress)) {
					this.OnPropertyChanging("GateKeeperIPAddress", this._gateKeeperIPAddress);
					this._gateKeeperIPAddress = value;
					this.OnPropertyChanged("GateKeeperIPAddress");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Useragent", Storage="_gateKeeperUseragent", FieldType="Text")]
		public string GateKeeperUseragent {
			get {
				return this._gateKeeperUseragent;
			}
			set {
				if ((value != this._gateKeeperUseragent)) {
					this.OnPropertyChanging("GateKeeperUseragent", this._gateKeeperUseragent);
					this._gateKeeperUseragent = value;
					this.OnPropertyChanged("GateKeeperUseragent");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Referrer", Storage="_gateKeeperReferrer", FieldType="Text")]
		public string GateKeeperReferrer {
			get {
				return this._gateKeeperReferrer;
			}
			set {
				if ((value != this._gateKeeperReferrer)) {
					this.OnPropertyChanging("GateKeeperReferrer", this._gateKeeperReferrer);
					this._gateKeeperReferrer = value;
					this.OnPropertyChanged("GateKeeperReferrer");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Type", Storage="_gateKeeper_Type", FieldType="Choice")]
		public System.Nullable<GateKeeper_Type> GateKeeper_Type {
			get {
				return this._gateKeeper_Type;
			}
			set {
				if ((value != this._gateKeeper_Type)) {
					this.OnPropertyChanging("GateKeeper_Type", this._gateKeeper_Type);
					this._gateKeeper_Type = value;
					this.OnPropertyChanged("GateKeeper_Type");
				}
			}
		}
	}
	
	/// <summary>
	/// Create a new list item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="GateKeeper Entry", Id="0x0100FE525E38AA64A640B310538E993529C8")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(GateKeeperGateKeeperEntry))]
	public partial class GateKeeperEntry : Item {
		
		private string _gateKeeperIPAddress;
		
		private string _gateKeeperUseragent;
		
		private string _gateKeeperUrl;
		
		private System.Nullable<System.DateTime> _gateKeeperDate;
		
		private string _gateKeeperComment;
		
		private System.Nullable<GateKeeper_Type> _gateKeeper_Type;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public GateKeeperEntry() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_IPAddress", Storage="_gateKeeperIPAddress", FieldType="Text")]
		public string GateKeeperIPAddress {
			get {
				return this._gateKeeperIPAddress;
			}
			set {
				if ((value != this._gateKeeperIPAddress)) {
					this.OnPropertyChanging("GateKeeperIPAddress", this._gateKeeperIPAddress);
					this._gateKeeperIPAddress = value;
					this.OnPropertyChanged("GateKeeperIPAddress");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Useragent", Storage="_gateKeeperUseragent", FieldType="Text")]
		public string GateKeeperUseragent {
			get {
				return this._gateKeeperUseragent;
			}
			set {
				if ((value != this._gateKeeperUseragent)) {
					this.OnPropertyChanging("GateKeeperUseragent", this._gateKeeperUseragent);
					this._gateKeeperUseragent = value;
					this.OnPropertyChanged("GateKeeperUseragent");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Url", Storage="_gateKeeperUrl", FieldType="Text")]
		public string GateKeeperUrl {
			get {
				return this._gateKeeperUrl;
			}
			set {
				if ((value != this._gateKeeperUrl)) {
					this.OnPropertyChanging("GateKeeperUrl", this._gateKeeperUrl);
					this._gateKeeperUrl = value;
					this.OnPropertyChanged("GateKeeperUrl");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Date", Storage="_gateKeeperDate", FieldType="DateTime")]
		public System.Nullable<System.DateTime> GateKeeperDate {
			get {
				return this._gateKeeperDate;
			}
			set {
				if ((value != this._gateKeeperDate)) {
					this.OnPropertyChanging("GateKeeperDate", this._gateKeeperDate);
					this._gateKeeperDate = value;
					this.OnPropertyChanged("GateKeeperDate");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Comment", Storage="_gateKeeperComment", FieldType="Text")]
		public string GateKeeperComment {
			get {
				return this._gateKeeperComment;
			}
			set {
				if ((value != this._gateKeeperComment)) {
					this.OnPropertyChanging("GateKeeperComment", this._gateKeeperComment);
					this._gateKeeperComment = value;
					this.OnPropertyChanged("GateKeeperComment");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Type", Storage="_gateKeeper_Type", FieldType="Choice")]
		public System.Nullable<GateKeeper_Type> GateKeeper_Type {
			get {
				return this._gateKeeper_Type;
			}
			set {
				if ((value != this._gateKeeper_Type)) {
					this.OnPropertyChanging("GateKeeper_Type", this._gateKeeper_Type);
					this._gateKeeper_Type = value;
					this.OnPropertyChanged("GateKeeper_Type");
				}
			}
		}
	}
	
	/// <summary>
	/// Create a new list item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="HoneyPot Entry", Id="0x0100B02A6273A93A75478BFFA53CC49ABA75")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(GateKeeperHoneyPotEntry))]
	public partial class HoneyPotEntry : Item {
		
		private System.Nullable<System.DateTime> _gateKeeperDate;
		
		private string _gateKeeperIPAddress;
		
		private string _gateKeeperUseragent;
		
		private string _gateKeeperReferrer;
		
		private System.Nullable<GateKeeper_Type> _gateKeeper_Type;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public HoneyPotEntry() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Date", Storage="_gateKeeperDate", FieldType="DateTime")]
		public System.Nullable<System.DateTime> GateKeeperDate {
			get {
				return this._gateKeeperDate;
			}
			set {
				if ((value != this._gateKeeperDate)) {
					this.OnPropertyChanging("GateKeeperDate", this._gateKeeperDate);
					this._gateKeeperDate = value;
					this.OnPropertyChanged("GateKeeperDate");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_IPAddress", Storage="_gateKeeperIPAddress", FieldType="Text")]
		public string GateKeeperIPAddress {
			get {
				return this._gateKeeperIPAddress;
			}
			set {
				if ((value != this._gateKeeperIPAddress)) {
					this.OnPropertyChanging("GateKeeperIPAddress", this._gateKeeperIPAddress);
					this._gateKeeperIPAddress = value;
					this.OnPropertyChanged("GateKeeperIPAddress");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Useragent", Storage="_gateKeeperUseragent", FieldType="Text")]
		public string GateKeeperUseragent {
			get {
				return this._gateKeeperUseragent;
			}
			set {
				if ((value != this._gateKeeperUseragent)) {
					this.OnPropertyChanging("GateKeeperUseragent", this._gateKeeperUseragent);
					this._gateKeeperUseragent = value;
					this.OnPropertyChanged("GateKeeperUseragent");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Referrer", Storage="_gateKeeperReferrer", FieldType="Text")]
		public string GateKeeperReferrer {
			get {
				return this._gateKeeperReferrer;
			}
			set {
				if ((value != this._gateKeeperReferrer)) {
					this.OnPropertyChanging("GateKeeperReferrer", this._gateKeeperReferrer);
					this._gateKeeperReferrer = value;
					this.OnPropertyChanged("GateKeeperReferrer");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Type", Storage="_gateKeeper_Type", FieldType="Choice")]
		public System.Nullable<GateKeeper_Type> GateKeeper_Type {
			get {
				return this._gateKeeper_Type;
			}
			set {
				if ((value != this._gateKeeper_Type)) {
					this.OnPropertyChanging("GateKeeper_Type", this._gateKeeper_Type);
					this._gateKeeper_Type = value;
					this.OnPropertyChanged("GateKeeper_Type");
				}
			}
		}
	}
	
	/// <summary>
	/// Create a new list item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="HTTP Entry", Id="0x0100481213A85D86C04185CCC53E27B2E9DC")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(GateKeeperHTTPEntry))]
	public partial class HTTPEntry : Item {
		
		private System.Nullable<System.DateTime> _gateKeeperDate;
		
		private string _gateKeeperIPAddress;
		
		private string _gateKeeperThreatlevel;
		
		private string _gateKeeperVisitortype;
		
		private string _gateKeeperLastActivity;
		
		private string _gateKeeperUseragent;
		
		private string _gateKeeperReferrer;
		
		private System.Nullable<GateKeeper_Type> _gateKeeper_Type;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public HTTPEntry() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Date", Storage="_gateKeeperDate", FieldType="DateTime")]
		public System.Nullable<System.DateTime> GateKeeperDate {
			get {
				return this._gateKeeperDate;
			}
			set {
				if ((value != this._gateKeeperDate)) {
					this.OnPropertyChanging("GateKeeperDate", this._gateKeeperDate);
					this._gateKeeperDate = value;
					this.OnPropertyChanged("GateKeeperDate");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_IPAddress", Storage="_gateKeeperIPAddress", FieldType="Text")]
		public string GateKeeperIPAddress {
			get {
				return this._gateKeeperIPAddress;
			}
			set {
				if ((value != this._gateKeeperIPAddress)) {
					this.OnPropertyChanging("GateKeeperIPAddress", this._gateKeeperIPAddress);
					this._gateKeeperIPAddress = value;
					this.OnPropertyChanged("GateKeeperIPAddress");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Threatlevel", Storage="_gateKeeperThreatlevel", FieldType="Text")]
		public string GateKeeperThreatlevel {
			get {
				return this._gateKeeperThreatlevel;
			}
			set {
				if ((value != this._gateKeeperThreatlevel)) {
					this.OnPropertyChanging("GateKeeperThreatlevel", this._gateKeeperThreatlevel);
					this._gateKeeperThreatlevel = value;
					this.OnPropertyChanged("GateKeeperThreatlevel");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Visitortype", Storage="_gateKeeperVisitortype", FieldType="Text")]
		public string GateKeeperVisitortype {
			get {
				return this._gateKeeperVisitortype;
			}
			set {
				if ((value != this._gateKeeperVisitortype)) {
					this.OnPropertyChanging("GateKeeperVisitortype", this._gateKeeperVisitortype);
					this._gateKeeperVisitortype = value;
					this.OnPropertyChanged("GateKeeperVisitortype");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_LastActivity", Storage="_gateKeeperLastActivity", FieldType="Text")]
		public string GateKeeperLastActivity {
			get {
				return this._gateKeeperLastActivity;
			}
			set {
				if ((value != this._gateKeeperLastActivity)) {
					this.OnPropertyChanging("GateKeeperLastActivity", this._gateKeeperLastActivity);
					this._gateKeeperLastActivity = value;
					this.OnPropertyChanged("GateKeeperLastActivity");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Useragent", Storage="_gateKeeperUseragent", FieldType="Text")]
		public string GateKeeperUseragent {
			get {
				return this._gateKeeperUseragent;
			}
			set {
				if ((value != this._gateKeeperUseragent)) {
					this.OnPropertyChanging("GateKeeperUseragent", this._gateKeeperUseragent);
					this._gateKeeperUseragent = value;
					this.OnPropertyChanged("GateKeeperUseragent");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Referrer", Storage="_gateKeeperReferrer", FieldType="Text")]
		public string GateKeeperReferrer {
			get {
				return this._gateKeeperReferrer;
			}
			set {
				if ((value != this._gateKeeperReferrer)) {
					this.OnPropertyChanging("GateKeeperReferrer", this._gateKeeperReferrer);
					this._gateKeeperReferrer = value;
					this.OnPropertyChanged("GateKeeperReferrer");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Type", Storage="_gateKeeper_Type", FieldType="Choice")]
		public System.Nullable<GateKeeper_Type> GateKeeper_Type {
			get {
				return this._gateKeeper_Type;
			}
			set {
				if ((value != this._gateKeeper_Type)) {
					this.OnPropertyChanging("GateKeeper_Type", this._gateKeeper_Type);
					this._gateKeeper_Type = value;
					this.OnPropertyChanged("GateKeeper_Type");
				}
			}
		}
	}
	
	/// <summary>
	/// Create a new list item.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Proxy Entry", Id="0x0100B153CB75BEE5844580A0A78C49EE8ABF")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(GateKeeperProxyEntry))]
	public partial class ProxyEntry : Item {
		
		private System.Nullable<System.DateTime> _gateKeeperDate;
		
		private string _gateKeeperIPAddress;
		
		private string _gateKeeperUseragent;
		
		private string _gateKeeperReferrer;
		
		private System.Nullable<GateKeeper_Type> _gateKeeper_Type;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public ProxyEntry() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Date", Storage="_gateKeeperDate", FieldType="DateTime")]
		public System.Nullable<System.DateTime> GateKeeperDate {
			get {
				return this._gateKeeperDate;
			}
			set {
				if ((value != this._gateKeeperDate)) {
					this.OnPropertyChanging("GateKeeperDate", this._gateKeeperDate);
					this._gateKeeperDate = value;
					this.OnPropertyChanged("GateKeeperDate");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_IPAddress", Storage="_gateKeeperIPAddress", FieldType="Text")]
		public string GateKeeperIPAddress {
			get {
				return this._gateKeeperIPAddress;
			}
			set {
				if ((value != this._gateKeeperIPAddress)) {
					this.OnPropertyChanging("GateKeeperIPAddress", this._gateKeeperIPAddress);
					this._gateKeeperIPAddress = value;
					this.OnPropertyChanged("GateKeeperIPAddress");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Useragent", Storage="_gateKeeperUseragent", FieldType="Text")]
		public string GateKeeperUseragent {
			get {
				return this._gateKeeperUseragent;
			}
			set {
				if ((value != this._gateKeeperUseragent)) {
					this.OnPropertyChanging("GateKeeperUseragent", this._gateKeeperUseragent);
					this._gateKeeperUseragent = value;
					this.OnPropertyChanged("GateKeeperUseragent");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Referrer", Storage="_gateKeeperReferrer", FieldType="Text")]
		public string GateKeeperReferrer {
			get {
				return this._gateKeeperReferrer;
			}
			set {
				if ((value != this._gateKeeperReferrer)) {
					this.OnPropertyChanging("GateKeeperReferrer", this._gateKeeperReferrer);
					this._gateKeeperReferrer = value;
					this.OnPropertyChanged("GateKeeperReferrer");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GateKeeper_Type", Storage="_gateKeeper_Type", FieldType="Choice")]
		public System.Nullable<GateKeeper_Type> GateKeeper_Type {
			get {
				return this._gateKeeper_Type;
			}
			set {
				if ((value != this._gateKeeper_Type)) {
					this.OnPropertyChanging("GateKeeper_Type", this._gateKeeper_Type);
					this._gateKeeper_Type = value;
					this.OnPropertyChanged("GateKeeper_Type");
				}
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Drone Entry", Id="0x010046EA71B010823F4193BDCAC6F54AC4B3", List="GateKeeper")]
	public partial class GateKeeperDroneEntry : DroneEntry {
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public GateKeeperDroneEntry() {
			this.OnCreated();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override string Title {
			get {
				throw new System.InvalidOperationException("Field Title was removed from content type Drone Entry.");
			}
			set {
				throw new System.InvalidOperationException("Field Title was removed from content type Drone Entry.");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="GateKeeper Entry", Id="0x0100FE525E38AA64A640B310538E993529C8", List="GateKeeper")]
	public partial class GateKeeperGateKeeperEntry : GateKeeperEntry {
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public GateKeeperGateKeeperEntry() {
			this.OnCreated();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override string Title {
			get {
				throw new System.InvalidOperationException("Field Title was removed from content type GateKeeper Entry.");
			}
			set {
				throw new System.InvalidOperationException("Field Title was removed from content type GateKeeper Entry.");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="HoneyPot Entry", Id="0x0100B02A6273A93A75478BFFA53CC49ABA75", List="GateKeeper")]
	public partial class GateKeeperHoneyPotEntry : HoneyPotEntry {
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public GateKeeperHoneyPotEntry() {
			this.OnCreated();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override string Title {
			get {
				throw new System.InvalidOperationException("Field Title was removed from content type HoneyPot Entry.");
			}
			set {
				throw new System.InvalidOperationException("Field Title was removed from content type HoneyPot Entry.");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="HTTP Entry", Id="0x0100481213A85D86C04185CCC53E27B2E9DC", List="GateKeeper")]
	public partial class GateKeeperHTTPEntry : HTTPEntry {
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public GateKeeperHTTPEntry() {
			this.OnCreated();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override string Title {
			get {
				throw new System.InvalidOperationException("Field Title was removed from content type HTTP Entry.");
			}
			set {
				throw new System.InvalidOperationException("Field Title was removed from content type HTTP Entry.");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Proxy Entry", Id="0x0100B153CB75BEE5844580A0A78C49EE8ABF", List="GateKeeper")]
	public partial class GateKeeperProxyEntry : ProxyEntry {
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public GateKeeperProxyEntry() {
			this.OnCreated();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override string Title {
			get {
				throw new System.InvalidOperationException("Field Title was removed from content type Proxy Entry.");
			}
			set {
				throw new System.InvalidOperationException("Field Title was removed from content type Proxy Entry.");
			}
		}
	}
	
	public enum GateKeeper_Type : int {
		
		None = 0,
		
		Invalid = 1,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Drone")]
		Drone = 2,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Black")]
		Black = 4,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="White")]
		White = 8,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="HoneyPot")]
		HoneyPot = 16,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="HTTP")]
		HTTP = 32,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Proxy")]
		Proxy = 64,
	}
}
