// <copyright file="SPGateKeeperContext.cs" company="Hemrika">
// Copyright Hemrika. All rights reserved.
// </copyright>
// <author>MARKETING\Administrator</author>
// <date>2012-04-20 00:06:23Z</date>
// <auto-generated>
//   Generated with SharePoint Software Factory 3.2
// </auto-generated>
namespace Hemrika.SharePresence.WebSite.Modules.GateKeeper
{
    using System;
    using Microsoft.SharePoint;
    using System.Web;

    /// <summary>
    /// Generated class for access list via LINQ
    /// </summary>
    /// <example>
    /// Use the class as follows:
    ///
    /// // Get DataContext from page context
    /// SPGateKeeperContext data = new SPGateKeeperContext(SPContext.Current.Web.Url);
    ///
    /// // Get the SharePoint list
    /// EntityList<Drone Entry> GateKeeper = data.GetList<Drone Entry>("GateKeeper");
    ///
    /// Query for GateKeeper with a specified metadata  "searchedValue"
    /// var resultEntities = from entity in GateKeeper where entity.GateKeeper_Date == "searchedValue" select entity;
    /// </example>
    [System.CodeDom.Compiler.GeneratedCode("SPSF", "3.2")]
    public partial class SPGateKeeperContext
    {
        public SPGateKeeperContext()
            : this(SPContext.Current.Web.Url)
        {
        }

        partial void OnCreated()
        {
        }

        internal static void RunWithElevatedPrivilegesAndContextSwitch(SPSecurity.CodeToRunElevated secureCode)
        {
            HttpContext backupContext = HttpContext.Current;

            HttpContext.Current = null;
            SPSecurity.RunWithElevatedPrivileges(secureCode);

            HttpContext.Current = backupContext;
        }

    }
}

